### PR TITLE
Fix: haromize submittedAt - issue 118

### PR DESCRIPTION
**Pull request by Jean-Grimal**
Fixes https://github.com/cantinasec/review-morpho-blue-1/issues/118

### CODE REVIEW

**Comment by MerlinEgalite** [comment]
I'm wondering if it's necessary seeing the PR

**Comment by MerlinEgalite** [comment]
We acknowledge the issue

**Review by Rubilmax — APPROVED** [review]
In the end, I do think that providing the same type for all timestamps may be easier to interact with from an integrator's POV ; and it doesn't cost much

**Review by QGarchery — APPROVED** [review]
Agree to change it considering that we missed the implicit cast in this line (it should have been a `uint96` cast):
https://github.com/morpho-org/metamorpho/blob/95d4dcbcd4d95b8cfe3cbe2f7575d46d5572f210/src/MetaMorpho.sol#L252

**Review by MerlinEgalite — APPROVED** [review]

**Pull request merged**
