### PR TITLE
Rename `sortWithdrawQueue` -> `updateWithdrawQueue`

### PR DESCRIPTION
**Pull request by adhusson**

### CODE REVIEW

**Review by MerlinEgalite — APPROVED** [review]

**Review by MerlinEgalite — CHANGES_REQUESTED** [review]
Oh I think there's also in the readme no?

EDIT: there's none but there's `_sortSupplyQueueIdleLast` we may want to update though

**Review by Rubilmax — CHANGES_REQUESTED** [review]
also solves another issue (but i can't find which one)

**Comment by Jean-Grimal** [comment]
If I remember well it was originaly called  `sortWithdrawQueue` but was renamed `updateWithdrawQueue` during the spearbit audit (stermi asked for it I think)

**Review by Jean-Grimal — APPROVED** [review]

**Review by MerlinEgalite — APPROVED** [review]

**Comment by Jean-Grimal** [comment]
Fixed here : https://github.com/morpho-org/metamorpho/pull/345/files

So I close this PR to avoid conflicts.

**Pull request closed without merging**
